### PR TITLE
Feature/srch 3259 uswds banner footer

### PR DESCRIPTION
**Pull request by yogesh27**
## Summary
- Added the css and js for USWDS banner and footer components
- Added the banner and footer components
- Not using the vendor's uswds js, wrote the custom code in usdws.js to handle the banner toggle functionality
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks

- [x] You have run `bundle update` and committed your changes to Gemfile.lock.
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
 
- [x] You have squashed your commits into a single commit (exceptions: your PR includes commits with formatting-only changes, such as required by Rubocop or Cookstyle, or if this is a feature branch that includes multiple commits).
 
- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [x] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [x] You have specified at least one "Reviewer".

### CODE REVIEW

**Comment by yogesh27** [comment]
Code Climate failing due to css linting. All the css is from USWDS vendor, so we should be good.

**Comment by amanifarooque** [comment]
@yogesh27 remember to squash your commits into one (third checklist item)

**Comment by yogesh27** [comment]
@amanifarooque Sure. Actually, I was referring to the exception which says **if this is a feature branch that includes multiple commits**
Let me close this and do a fresh one.

**Comment by MothOnMars** [comment]
@yogesh27 , it looks like your text editor is stripping the newline from the end of files:
image

Can you update your text editor settings to ensure that files are saved with trailing newlines?

See: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by yogesh27** [comment]
> @yogesh27 , it looks like your text editor is stripping the newline from the end of files: image
> 
> Can you update your text editor settings to ensure that files are saved with trailing newlines?
> 
> See: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

Hi @MothOnMars 
I have fixed this issue and working on a new PR: https://github.com/GSA/search-gov/pull/988

**Pull request closed without merging**
