### PR TITLE
SRCH-3043 Parse and extract custom tags from html

### PR DESCRIPTION
**Pull request by lorawoodford**
## Summary
Initial pass at extracting searchgov_custom metadata from searchgov html documents (note: no metadata source for searchgov_custom in non-html documents exists per the v1 spreadsheet so this is an html documents change only). The future goal is to index 3 custom metadata fields (searchgov_custom1, searchgov_custom2, searchgov_custom3).  We will likely want to do some validation/inspection of the user-generated custom metadata content since it is intended for future facet creation (e.g. we don't want a paragraph of descriptive prose to be presented as a facet), but for now this just gets the skeleton of this work in place.

This PR:

- Updates `app/models/html_document.rb` to extract searchgov_custom metadata from the sources listed - searchgov_custom1, searchgov_custom2, and searchgov_custom3 (lines 20-24);
- Addresses several pre-existing code style issues in `app/models/html_document.rb` (all other modifications);
- Adds tests to confirm functionality of new searchgov_custom method in `app/models/html_document.rb`; and,
- Shuffles some `let`s under the shared test headings in `spec/models/html_document_spec.rb` to resolve some existing `Example group has too many memoized helpers` rubocop violations.

Note: Much of the above duplicates work PRed in #945 and #948 - this lets any PR enter main first.
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review:

#### Functionality Checks

- [x] Code is functional.

- [x] Automated checks pass, if applicable. If Code Climate checks do not pass, explain reason for failures:
Also includes several unrelated, pre-existing CodeClimate fixes in `app/models/html_document.rb`.

- [x] If your changes will be tested manually, you have run `bundle update` and committed your changes to Gemfile.lock.
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
 
- [x] If your target branch is NOT `main`, specify the reason:
 
- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release #.#.#** matching the release number
 
- [x] You have squashed your commits into a single commit (exception: your PR includes commits with formatting-only changes, such as required by Rubocop)

- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket
 
#### Process Checks

- [x] You have specified an "Assignee", and if necessary, additional reviewers

### CODE REVIEW

**Review by danswick — APPROVED** [review]
These changes look reasonable to me! Just one small (non-blocking) follow-up question, partly out of curiosity: do we have any expectations about the attribute value of the `custom[x]` meta tags that we want to test for here? Or is it safe to assume that any valid attribute is ok to pass through?

**Comment by lorawoodford** [comment]
@MothOnMars - As mentioned in standup, CC is failing due to the count of methods in the HtmlDocument class being greater than 20.  I'm suggesting we "Approve" this as is (@danswick can do the actual approval), and I'll make a chore to adjust `.codeclimate.yml` to remove this check.

Note: this failing check is not part of rubocop itself (why it wasn't being flagged in my IDE), but part of CodeClimate's "Structure" checks, so I can only see the failure from within codeclimate and/or when running codeclimate locally (`codeclimate analyze -e structure app/models/html_document.rb`).  The change in this branch resolves this issue (and 8 other incidences of the same): https://github.com/lorawoodford/search-gov/commit/9387ce88fa683f95b87c7ce40db9e99ce60d6665

**Comment by lorawoodford** [comment]
Ok, @danswick based on the above can you Approve the single code climate issue for me when you have a chance?  Thanks!

**Comment by lorawoodford** [comment]
D'oh, looks like it'll need a reapproval here in GH as well, @danswick .

**Review by danswick — APPROVED** [review]
re-approving after the code climate approval triggered the need for a new approval 🙃

**Pull request merged**
