### PR TITLE
SRCH-2686 upgrade gems for compatibility with Rails 6.1

### PR DESCRIPTION
**Pull request by MothOnMars**
## Summary
SRCH-2686 upgrade gems for compatibility with Rails 6.1
- update specs for compatibility with shoulda-matchers 5.x
- loosen version constraints for test & dev gems
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review:

#### Functionality Checks

- [x] Code is functional. 

- [x] Automated checks pass, if applicable. If Code Climate checks do not pass, explain reason for failures: Both failures are false positives:
- 6.0.4.4 is not a vulnerable version for "Possible Open Redirect in Host Authorization Middleware"
- we do not use Postgres, so we are not vulnerable to "Possible DoS Vulnerability in Active Record PostgreSQL adapter"

If that explanation is sufficient, you can visit https://codeclimate.com/github/GSA/search-gov/pull/835 and click the "Approve" button (be sure to log into CodeClimate via Github).

- [x] If your changes will be tested manually, you have run `bundle update` and committed your changes to Gemfile.lock.
 
- [x] You have merged the latest changes from the target branch (usually `master` or `main`) into your branch.
 
- [x] If your target branch is NOT `master` or `main`, specify the reason: target branch is `feature/rails_6_1`, as these changes are required for and will be tested as part of the Rails 6.1 upgrade
 
- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release #.#.#** matching the release number
 
- [x] You have squashed your commits into a single commit (exception: your PR includes commits with formatting-only changes, such as required by Rubocop)

- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket
 
#### Process Checks

- [x] You have specified an "Assignee", and if necessary, additional reviewers

### CODE REVIEW

**Comment by MothOnMars** [comment]
CircleCi is still on the fritz, so here are the test results:
image

**Comment by lorawoodford** [comment]
@MothOnMars Should the `bundler-audit` failures that weren't automatically fixed be investigated/addressed further now?  Aside from those, this LGTM.

**Comment by MothOnMars** [comment]
> @MothOnMars Should the `bundler-audit` failures that weren't automatically fixed be investigated/addressed further now? Aside from those, this LGTM.

See my notes in the PR. Those are both false positives, which you can approve in CodeClimate.

**Comment by lorawoodford** [comment]
LGTM.

**Pull request merged**
