### PR TITLE
SRCH-1265 Dockerize development environment

### PR DESCRIPTION
**Pull request by MothOnMars**
- make Elasticsearch 6.8 the default in development & CircleCi
- remove references to Travis CI
- fix DocumentFetcher spec
- remove VCR recordings of Tika requests

### CODE REVIEW

**Comment by ondrae** [comment]
- I already had mysql running from homebrew, to turn it off I had to use `launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.mysql@5.6.plist`.
- Seeing some `Mysql2::Error: Unknown database 'usasearch_development'` errors when running `docker-compose up`

**Comment by ondrae** [comment]
Got it all up and working, with passing specs. That was such a nicer setup.  I'll do a code review tomorrow.

**Comment by ondrae** [comment]
I had to run `docker-compose up` several times for the resque containers to stay up. Here are some of the different errors I've seen.
```
bundler: failed to load command: resque-web (/gems/bin/resque-web)
resque-web_1        | Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/pids/server.pid

**Comment by MothOnMars** [comment]
Closing this up while I remove the code to dockerize the app itself.

**Comment by MothOnMars** [comment]
@jmax-fearless , this is finally ready for re-review. Notable changes since this was last reviewed by Andrew:
- REAME updates
- update the Docker & Kibana image versions
- tweaks to our autodiscovery cucumber test, which was causing problems with the VCR cassettes

**Pull request merged**
