### PR TITLE
SRCH-372 - Update Rails to compile assets

### PR DESCRIPTION
**Pull request by peggles2**
SRCH-372 - Update Rails to compile the assets in the application itself. 
SRCH-355 - Update compass-rails gem.

### CODE REVIEW

**Comment by MothOnMars** [comment]
LGTM 👍

**Comment by peggles2** [comment]
I added compass gem. Please review again. Thanks!

**Comment by MothOnMars** [comment]
LGTM 👍 

Note: When you merge this, be sure to include both JIRA tix in the first line of the commit, i.e.:
```
SRCH-372 SRCH-355 - Update Rails to compile assets
- update compass-rails to 3.1.0
```

**Comment by peggles2** [comment]
Thats really long commit message.

**Comment by MothOnMars** [comment]
Including both commits on the first line will ensure that they are auto-associated with the appropriate JIRA issues in JIRA itself.

**Pull request merged**
