### PR TITLE
SRCH-4055 remove code and specs related to Twitter

### PR DESCRIPTION
**Pull request by MothOnMars**
## Summary
SRCH-4055 remove code and specs related to Twitter
- update gems
- remove unused gems

Database tables & columns will be backed up and then dropped in a follow-up story.
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [x] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [x] You have specified at least one "Reviewer".

### CODE REVIEW

**Review by lorawoodford — CHANGES_REQUESTED** [review]
Two (very minor) recommendations to clean up the test suites so as to not trip up future devs, but on the whole looks great:

- lns 29 and 44 of `spec/views/shared/_autodiscovery.html.haml_spec.rb` should be dumped;
- lns 3 - 53 of `features/vcr_cassettes/Dashboard/Adding_a_new_site.yml` could be deleted (but if you disagree with cleaning up/altering cassettes, I'm happy to accept this as is... just a suggestion)

**Comment by MothOnMars** [comment]
Thanks, @lorawoodford ! Good catches.

**Review by lorawoodford — DISMISSED** [review]
LGTM

**Comment by MothOnMars** [comment]
@lorawoodford , re-review needed. I have removed the problematic initializer, which was causing connection problems in staging. It appears to have been intended to support EventMachine, which was only used by our Twitter integration.

**Review by lorawoodford — APPROVED** [review]
LGTM

**Pull request merged**
