### PR TITLE
SRCH-4170 add hashed_url column to searchgov_urls

### PR DESCRIPTION
**Pull request by MothOnMars**
## Summary
This PR is the first step required to properly de-duplicate `SearchgovUrl` records. This adds a `document_id` column to the `searchgov_urls` table and ensures that the `document_id` is set on record creation. Once this column is in the production table, I'll update the data for the existing records and purge any duplicates. A final PR will set set the `document_id` column as non-nullable and add a unique index on that column.
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [x] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [x] You have specified at least one "Reviewer".

### CODE REVIEW

**Review by lorawoodford — DISMISSED** [review]
LGTM.

My only question was going to be about the choice of `document_id` for this.  It could be easily confused with the - as-of-yet unused - searchgov_documents table which itself has an id as well as all the other types and ways we reference "documents."  Then I realized this isn't net new, just the implementation is changing.  So, makes sense to stick with `document_id`.

**Comment by MothOnMars** [comment]
@lorawoodford , that's a good point. While it's true that `document_id` isn't new, it's *also* true that our code is getting more and more crowded with various `document`-y things. It may avoid confusion if I use a more distinctive, descriptive name such as `hashed_url`. I'm going to noodle this a bit before moving forward on this story and the follow-up stories that depend on this change.

**Comment by MothOnMars** [comment]
@lorawoodford , this is ready for a re-review. I've renamed the `document_id` column to `hashed_url`. That actually simplifies the deployment of this story, because the existing `document_id` method will continue to work for indexing until I've done the necessary follow-up work referenced in the comments.

**Review by lorawoodford — APPROVED** [review]
LGTM

**Pull request merged**
