### PR TITLE
SRCH-5141 Removing Ruby 3.0 and MySQL 5.7 from Circle CI

### PR DESCRIPTION
**Pull request by linuxcomputergeek**
SRCH-5141 Removing Ruby 3.0 and MySQL 5.7 from Circle CI

## Summary
- Updating CircleCI to only use Ruby 3.1.4
- Updating CircleCI to only use MySQL 8.0

 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [x] You have specified at least one "Reviewer".

### CODE REVIEW

**Comment by linuxcomputergeek** [comment]
I noticed on making this change that The Jest on line 369 still uses MySQL 5.7, should this be changed to be 8.0?

**Comment by lorawoodford** [comment]
@linuxcomputergeek One addition request to what you've already got here.  In reviewing #1549 I realized that our existing requirements under the report coverage job are going to essentially block us from merging any code that has failing tests under non-production/non-required ruby, mysql, and/or node versions.  At present, those requirements (very bottom of config.yml) look like:

```
      - report_coverage:
          requires:
            - rspec
            - cucumber
            - jest
          name: "report coverage: Ruby << matrix.ruby_version >>, ES << matrix.elasticsearch_version >>, MySQL << matrix.mysql_version >>"
          matrix:
            parameters:
              ruby_version:
                - 3.0.6
                - 3.1.4
              elasticsearch_version:
                - 7.17.7
              mysql_version:
                - "5.7"
                - "8.0"
```

Since we are requiring jobs based on the non-matrixed names, if _any_ job in that matrix fails to pass, we will never run _any_ job in the report coverage group.  We need to update that block to: 

```
      - report_coverage:
          requires:
            - "rspec: Ruby << matrix.ruby_version >>, ES << matrix.elasticsearch_version >>, MySQL << matrix.mysql_version >>"
            - "cucumber: Ruby << matrix.ruby_version >>, ES << matrix.elasticsearch_version >>, MySQL << matrix.mysql_version >>"
            - "jest: NodeJS << matrix.node_version >>, Ruby << matrix.ruby_version >>, MySQL << matrix.mysql_version >>"
          name: "report coverage: Ruby << matrix.ruby_version >>, ES << matrix.elasticsearch_version >>, MySQL << matrix.mysql_version >>, NodeJS << matrix.node_version >>"
          matrix:
            parameters:
              ruby_version:
                - 3.0.6
                - 3.1.4
              elasticsearch_version:
                - 7.17.7
              mysql_version:
                - "5.7"
                - "8.0"
              node_version:
                - 16.20.2
```

We'll also need to ensure a node_version argument is also added up under the report_coverage job parameters.

Thanks!

**Comment by linuxcomputergeek** [comment]
@lorawoodford I'm confused by the changes you mentioned in your previous comment, I think I've made the appropriate changes and have everything commited, but I don't see that the required tests are passing?

**Comment by lorawoodford** [comment]
@linuxcomputergeek This looks like I'd expect (except you still need to update from main).

The test issues you're now seeing are because the required checks will need to be updated by @jimkreft (no dev has access to do this).  You'll need him to require:

- jest: NodeJS 16.20.2, Ruby 3.1.4, MySQL 8.0
- report coverage: Ruby 3.1.4, ES 7.17.7, MySQL 8.0, NodeJS 16.20.2

and remove the requirements for:
- jest: NodeJS 16.20.2, Ruby 3.1.4, MySQL 5.7 (this no longer exists)
- report coverage: Ruby 3.1.4, ES 7.17.7, MySQL 8.0 (this has been renamed to include node version)

**Review by lorawoodford — APPROVED** [review]
@linuxcomputergeek LGTM but you won't be able to merge until you get @jimkreft to update those branch protections (and you take this off draft).

**Pull request merged**
