### PR TITLE
SRCH-1564 "db:seed" should run automatically on new/rebuilt staging databases

### PR DESCRIPTION
**Pull request by bendahrooge**
## Summary
- Enables automatically seeding the MySQL database in staging environments using environment variable override
- See cookbooks PR 636 for more information  
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks

- [X] You have run `bundle update` and committed your changes to Gemfile.lock.
 
- [X] You have merged the latest changes from the target branch (usually `main`) into your branch.
 
- [x] You have squashed your commits into a single commit (exceptions: your PR includes commits with formatting-only changes, such as required by Rubocop or Cookstyle, or if this is a feature branch that includes multiple commits).
 
- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [x] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [x] You have specified at least one "Reviewer".

### CODE REVIEW

**Review by jamesmadhoc — APPROVED** [review]
I have one small misgiving: the name of the boolean env. var., "SEED", is pretty ambiguous, which might lead to it being inadvertently set somewhere else.  It would be nice if it looked like a boolean (in Ruby a '?' or in Lisp a 'p' at the end, for "predicate") *and* if gave a clue to its usage context, something like "SHOULD_DB_SEED_STAGING".

All that said, it's just a small concern, and if you changed it here you'd have to also change it over in the cookbooks (I think), so I'll approve the change.

**Comment by bendahrooge** [comment]
Thanks for the comments @jamesmadhoc, I agree that the environment variable name should be more descriptive. I've updated both PRs to address this.

**Review by jamesmadhoc — DISMISSED** [review]
LGTM

**Comment by bendahrooge** [comment]
@jamesmadhoc Since I am without write access on this repo, when you get a chance, could you please merge this PR? Acceptance testing for SRCH-1564 was completed this afternoon.

**Review by jamesmadhoc — APPROVED** [review]
LGTM

**Pull request merged**
