### PR TITLE
Removed webrat

### PR DESCRIPTION
**Pull request by HalahAb**
Fixed https://github.com/GSA/search-gov/issues/37

### CODE REVIEW

**Comment by nickmarden** [comment]
@HalahAb thanks for the PR! Can you simply remove webrat rather than commenting it out? If we ever want the code back, that's what `git revert` is for :-)

Also, I can't understand why this change requires a new VCR cassette to be created. Could you provide some explanation of why that yml file gets added as part of this PR?

**Comment by HalahAb** [comment]
Hello @nickmarden!

I’ve updated the PR and removed the comments.

The cassette was generated after I had run the tests locally. It was generated after running spec/models/searchgov_url_spec.rb:422.

Looking through the most recent change for this spec (https://github.com/GSA/search-gov/commit/99756e58795c4549f2ddddeebab9f15ad4663eca#diff-efcce6238f2ec3698b732de1464b4613L426) omitting `vcr: { re_record_interval: nil }` seems to be generating it now.

Also, the build is now failing on Circle and I’m now looking into that.

**Comment by MothOnMars** [comment]
@nickmarden , the RR fork of search-gov is missing the latest few commits in search-gov master, including the commit that changed the VCR config. I'll update the RR fork, so that @HalahAb (welcome!) can rebase the latest changes. That may also resolve the CircleCI errors.

**Comment by MothOnMars** [comment]
@HalahAb , I've updated the RR fork, so you can rebase. Re-running `spec/models/searchgov_url_spec.rb` should not update any VCR cassettes.

**Comment by nickmarden** [comment]
(Actually it looks as though it was already current against GSA/master, even if RapidRiverSoftware/master was not.)

**Pull request merged**
