### PR TITLE
[#153910285] index urls from a sitemap

### PR DESCRIPTION
**Pull request by MothOnMars**

### CODE REVIEW

**Comment by noremmie** [comment]
LGTM! 👍

**Comment by noremmie** [comment]
5bee990433fc2cdc27a62e56e7276cafe5e7dd7e LGTM too 👍

**Comment by MothOnMars** [comment]
@noremmie , sorry for the late-coming commits. I swear that's the last! (I also still intend to DRY up my logging, but that will have to wait until we're not in such a crunch.)

**Comment by noremmie** [comment]
826ca62921584daa258452a2996c3c5c33d606d7 LGTM too 👍 And no worries about the late-coming commits or crunchy un-DRYness! Also, I'm looking forward to parsing even more goodies our of our Rails logs 💖

**Comment by noremmie** [comment]
3406d70178b213ba885d5b788b4d00abf1ae46a4 LGTM too 👍

**Pull request merged**
